###################################
## Lincoln Loop Base Sass Lint File
###################################
# Linter Options
# rules @ https://github.com/sasstools/sass-lint/tree/master/docs/rules

files:
  include: 'src/sass/**/*.s+(a|c)ss'
  ignore: 'src/sass/vendor/**/*.scss'
options:
  # Don't merge default rules
  merge-default-rules: false
# Rule Configuration
rules:
  border-zero:
    - 2
    -
      convention: none
  brace-style:
    - 2
    -
      style: '1tbs'
  class-name-format:
    - 2
    - convention: hyphenatedlowercase
  clean-import-paths:
    - 2
    - filename-extension: false
  empty-args: 2
  empty-line-between-blocks:
    - 2
  extends-before-declarations: 2
  function-name-format:
    - 2
    - 
      convention: hyphenatedlowercase
  no-extends: 0
  mixin-name-format:
    - 2
    -
      convention: hyphenatedlowercase
  nesting-depth:
    - 1
    -
      max-depth: 5
  no-duplicate-properties: 1
  no-empty-rulesets: 2
  no-debug: 1
  no-ids: 1
  no-important: 2
  no-invalid-hex: 2
  no-misspelled-properties: 2
  no-vendor-prefixes: 0
  one-declaration-per-line: 2
  hex-notation:
    - 2
    -
      style: lowercase
  indentation:
    - 2
    -
      size: 4
  url-quotes: 2
  single-line-per-selector: 2
  space-around-operator: 2
  space-after-colon: 2
  space-before-brace: 2
  space-before-bang: 2
  space-before-colon: 2
  space-between-parens: 2
  zero-unit:
    - 2